@port=3001
@host=http://localhost:{{port}}/api


GET {{host}}/user/me
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMzNTU4NjdiMzVmZDA3OWIxNGNlOTEiLCJhZG1pbiI6ZmFsc2UsImRvZ1RyYWluZXIiOnRydWUsImRvZ1dhbGtlciI6dHJ1ZSwiaWF0IjoxNjUwNzIzOTU4fQ.cQoDVkEmLBXj4I2VNMdV-Vz4wJh5a7Qn4LFn8fA7Jgg


###

POST  {{host}}/user
Content-Type: application/json

{
     "firstName":"mousa",
     "lastName":"hammad",
    "email":"m1@m.com",
    "city":"jerusalem",
    "password":"123456",
    "gender":"זכר",
    "dateBirthDay":"01/01/1994",
    "admin":true,
    "dogTrainer":true,
    "dogWalker":true,
    "image":"https://images.app.goo.gl/C9RQ7Jg6HVJtN48m6",
    "phone":"052789456"
    
}
###

PUT {{host}}/user
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMzNTU4NjdiMzVmZDA3OWIxNGNlOTEiLCJhZG1pbiI6ZmFsc2UsImRvZ1RyYWluZXIiOnRydWUsImRvZ1dhbGtlciI6dHJ1ZSwiaWF0IjoxNjUwNzIzOTU4fQ.cQoDVkEmLBXj4I2VNMdV-Vz4wJh5a7Qn4LFn8fA7Jgg
Content-Type: application/json

{
    "firstName":"mousa",
     "lastName":"hammad",
    "email":"mm@mgddfd900.com",
    "city":"jerusalem",
    "gender":"זכר",
    "dateBirthDay":"01/01/1994",
    "admin":true,
    "dogTrainer":true,
    "dogWalker":true,
    "image":"https://images.app.goo.gl/C9RQ7Jg6HVJtN48m6",
    "phone":"052789456"

}

###

POST {{host}}/auth
Content-Type: application/json

{
    "email":"m@m.com",
    "password":"123456"
}

###
POST {{host}}/user/forgot-password
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjUxNmM4YTE0OWIzNDY5ZjYzMDFlYTgiLCJhZG1pbiI6ZmFsc2UsImRvZ1RyYWluZXIiOnRydWUsImRvZ1dhbGtlciI6dHJ1ZSwiaWF0IjoxNjQ5NTg3NDI1fQ.IAQTGik7x6JY1iSKH-de6qRAZEnF3eeu1Ms9yPPS8zA
Content-Type: application/json

{
    "email":"mousa909@outlook.co.il"
}

###

PUT {{host}}/user/reset-password
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjUxNmM4YTE0OWIzNDY5ZjYzMDFlYTgiLCJhZG1pbiI6ZmFsc2UsImRvZ1RyYWluZXIiOnRydWUsImRvZ1dhbGtlciI6dHJ1ZSwiaWF0IjoxNjQ5NTg3NDI1fQ.IAQTGik7x6JY1iSKH-de6qRAZEnF3eeu1Ms9yPPS8zA

{
    "_id":"6245a480bb51fdd508e28755",
    "tokenRef":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjUxNmM4YTE0OWIzNDY5ZjYzMDFlYTgiLCJhZG1pbiI6ZmFsc2UsImRvZ1RyYWluZXIiOnRydWUsImRvZ1dhbGtlciI6dHJ1ZSwiaWF0IjoxNjQ5NTAzNDMyLCJleHAiOjE2NDk1MDQzMzJ9.b0gjVPVGeBWPpw6wf0KzQQG5-h_Haq9lFmkE0cM13y0",
    "password":"1234567"
}





###

GET {{host}}/user/me 
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZkMTkzYjg0MWE0ZjhmNWE5NWExMDciLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjp0cnVlLCJpYXQiOjE2NTEzMTcwNjB9.x9HQC5wZvN7mHsNgSZw1M1qH_4X_2MLHQ1aQ-9hVSP8

###
GET {{host}}/user 
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMzMDMyZGU4YjE1ZWY1MzZkZTQwZGMiLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjp0cnVlLCJpYXQiOjE2NDc1MTAzMzR9.ukN8Qn0OnJyl3O4Ht0z6QLxhgvLxm1w62HW8RPn3UHE

###
GET {{host}}/user/622cb12829b73ffbbf4a3903
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMzMDMyZGU4YjE1ZWY1MzZkZTQwZGMiLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjp0cnVlLCJpYXQiOjE2NDc1MTAzMzR9.ukN8Qn0OnJyl3O4Ht0z6QLxhgvLxm1w62HW8RPn3UHE





###

GET  {{host}}/cardTrain
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMzNTU4NjdiMzVmZDA3OWIxNGNlOTEiLCJhZG1pbiI6ZmFsc2UsImRvZ1RyYWluZXIiOnRydWUsImRvZ1dhbGtlciI6dHJ1ZSwiaWF0IjoxNjQ3NTMxNDI3fQ.fv-dIrUuE1C0XvwH2p_jXbwg1LXnh7Cqqv5JX2_1g84

###
GET  {{host}}/cardTrain/623355b57b35fd079b14ce95
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMzNTU4NjdiMzVmZDA3OWIxNGNlOTEiLCJhZG1pbiI6ZmFsc2UsImRvZ1RyYWluZXIiOnRydWUsImRvZ1dhbGtlciI6dHJ1ZSwiaWF0IjoxNjUwNzIzOTU4fQ.cQoDVkEmLBXj4I2VNMdV-Vz4wJh5a7Qn4LFn8fA7Jgg



   

###
POST  {{host}}/cardTrain
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZkMTkzYjg0MWE0ZjhmNWE5NWExMDciLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjp0cnVlLCJpYXQiOjE2NTEzMTcwNjB9.x9HQC5wZvN7mHsNgSZw1M1qH_4X_2MLHQ1aQ-9hVSP8
Content-Type: application/json

{
    "experience":5,
    "trainWay":true,
    "cost":"100-200",
    "timeTrain":1.5,
    "meets":{
    "sun": { "start": "", "end": "", "closed": true },
    "mon": { "start": "", "end": "", "closed": true },
    "tues": { "start": "", "end": "", "closed": true },
    "wen": { "start": "", "end": "", "closed": true },
    "turs": { "start": "", "end": "", "closed": true },
    "fri": { "start": "", "end": "", "closed": true },
    "sat": { "start": "", "end": "", "closed": true }
  }

}

###

put  {{host}}/cardTrain/626d1956841a4f8f5a95a10b
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZkMTkzYjg0MWE0ZjhmNWE5NWExMDciLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjp0cnVlLCJpYXQiOjE2NTEzMTcwNjB9.x9HQC5wZvN7mHsNgSZw1M1qH_4X_2MLHQ1aQ-9hVSP8
Content-Type: application/json

{
    "experience":5,
    "trainWay":false,
    "cost":"100-200",
    "timeTrain":2,
    "meets":{
    "sun": { "start": "", "end": "", "closed": true },
    "mon": { "start": "", "end": "", "closed": true },
    "tues": { "start": "", "end": "", "closed": true },
    "wen": { "start": "", "end": "", "closed": true },
    "turs": { "start": "", "end": "", "closed": true },
    "fri": { "start": "", "end": "", "closed": true },
    "sat": { "start": "", "end": "", "closed": true }
  }

}

###
delete  {{host}}/cardTrain/6233036be8b15ef536de40e4
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMzMDMyZGU4YjE1ZWY1MzZkZTQwZGMiLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjp0cnVlLCJpYXQiOjE2NDc1MTAzMzR9.ukN8Qn0OnJyl3O4Ht0z6QLxhgvLxm1w62HW8RPn3UHE
Content-Type: application/json

###

PATCH {{host}}/cardTrain/addT
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZkMTNmMjg3NjJhNGE2YTc3OTRlZWQiLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjp0cnVlLCJpYXQiOjE2NTIxMTIwMDN9.iMcVDCealdQhrE97tf8xVLR7uM5X8voDmP3dzNU2P0A
Content-Type: application/json

{
    "fDogTrainer":["2341545","dfsdfgdfg","2344545"]
}

###

PATCH   {{host}}/cardTrain/deleteT
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZkMTNmMjg3NjJhNGE2YTc3OTRlZWQiLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjp0cnVlLCJpYXQiOjE2NTIxMTIwMDN9.iMcVDCealdQhrE97tf8xVLR7uM5X8voDmP3dzNU2P0A
Content-Type: application/json

{
    "fDogTrainer":["2344545","dfsdfgdfg","2341545"]
}

###

GET {{host}}/cardTrain/checkFvCard/2344545
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZkMTNmMjg3NjJhNGE2YTc3OTRlZWQiLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjp0cnVlLCJpYXQiOjE2NTIxMTIwMDN9.iMcVDCealdQhrE97tf8xVLR7uM5X8voDmP3dzNU2P0A
Content-Type: application/json


###


POST {{host}}/cardTrain/updateMeet/623355b57b35fd079b14ce95
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMzNTU4NjdiMzVmZDA3OWIxNGNlOTEiLCJhZG1pbiI6ZmFsc2UsImRvZ1RyYWluZXIiOnRydWUsImRvZ1dhbGtlciI6dHJ1ZSwiaWF0IjoxNjQ3NTMxNDI3fQ.fv-dIrUuE1C0XvwH2p_jXbwg1LXnh7Cqqv5JX2_1g84
Content-Type: application/json

{

    
"sun":[{"ava":false},{"time":"10-11","ava":true}],
"mon":[{"ava":true},{"time":"10-11","ava":true}],
"tues":[{"ava":true},{"time":"10-11","ava":true}],
"wen":[{"ava":true},{"time":"10-11","ava":true}],
"turs":[{"ava":true},{"time":"10-11","ava":true}],
"fri":[{"ava":true},{"time":"10-11","ava":true}],
"sat":[{"ava":true},{"time":"10-11","ava":true}]
    
}

###

GET  {{host}}/cardWalk/
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMzNTU4NjdiMzVmZDA3OWIxNGNlOTEiLCJhZG1pbiI6ZmFsc2UsImRvZ1RyYWluZXIiOnRydWUsImRvZ1dhbGtlciI6dHJ1ZSwiaWF0IjoxNjQ3NTMxNDI3fQ.fv-dIrUuE1C0XvwH2p_jXbwg1LXnh7Cqqv5JX2_1g84


###


GET  {{host}}/cardWalk/byUser/626d13f28762a4a6a7794eed
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZkMTNmMjg3NjJhNGE2YTc3OTRlZWQiLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjp0cnVlLCJpYXQiOjE2NTE5MDE4NjV9.VnN6RQ1fdGnKGfyJBHfOuOJU6xlCylJJl3fvlI2rnc4

###
GET  {{host}}/cardWalk/623356f17b35fd079b14cea5
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMzNTU4NjdiMzVmZDA3OWIxNGNlOTEiLCJhZG1pbiI6ZmFsc2UsImRvZ1RyYWluZXIiOnRydWUsImRvZ1dhbGtlciI6dHJ1ZSwiaWF0IjoxNjQ3NTMxNDI3fQ.fv-dIrUuE1C0XvwH2p_jXbwg1LXnh7Cqqv5JX2_1g84


###
POST  {{host}}/cardWalk
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMzNTU4NjdiMzVmZDA3OWIxNGNlOTEiLCJhZG1pbiI6ZmFsc2UsImRvZ1RyYWluZXIiOnRydWUsImRvZ1dhbGtlciI6dHJ1ZSwiaWF0IjoxNjQ3NTMxNDI3fQ.fv-dIrUuE1C0XvwH2p_jXbwg1LXnh7Cqqv5JX2_1g84
Content-Type: application/json

{
    "experience":5,
    "cost":"100-200",
    "timeWalker":1.5

}

###
put  {{host}}/cardWalk/623356f17b35fd079b14cea5
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjJjYjEyODI5YjczZmZiYmY0YTM5MDMiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjQ3NTMxNTU1fQ.Sw1L3h0QL4I6QBmprOftR9gykiff7VGAiKYj7u2MBnw
Content-Type: application/json

{
    "experience":7,
    "cost":"100-200",
    "timeWalker":1.5

}

###
GET  {{host}}/cardWalk/getAllFavoriteWalker
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjdmYjQxYWY3N2FhYjUwOGNjZmQ2ZjkiLCJhZG1pbiI6ZmFsc2UsImRvZ1RyYWluZXIiOmZhbHNlLCJkb2dXYWxrZXIiOnRydWUsImlhdCI6MTY1MjYzODA2OX0.dZWgdusSIp_xY3FMPjNs_JofiSPcAS9SnMvF-XVZ0HA
Content-Type: application/json



###
delete  {{host}}/cardWalk/623356707b35fd079b14cea0
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjdmYjQxYWY3N2FhYjUwOGNjZmQ2ZjkiLCJhZG1pbiI6ZmFsc2UsImRvZ1RyYWluZXIiOmZhbHNlLCJkb2dXYWxrZXIiOnRydWUsImlhdCI6MTY1MjYzODA2OX0.dZWgdusSIp_xY3FMPjNs_JofiSPcAS9SnMvF-XVZ0HA
Content-Type: application/json

###

PATCH {{host}}/cardWalk/addW
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZkMTNmMjg3NjJhNGE2YTc3OTRlZWQiLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjp0cnVlLCJpYXQiOjE2NTIxMTIwMDN9.iMcVDCealdQhrE97tf8xVLR7uM5X8voDmP3dzNU2P0A
Content-Type: application/json

{
    "fDogWalker":["2334545","dfsdfgdfg","2344545"]
}

###
GET {{host}}/cardWalk/checkFvCard/2334545
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZkMTNmMjg3NjJhNGE2YTc3OTRlZWQiLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjp0cnVlLCJpYXQiOjE2NTIxMTIwMDN9.iMcVDCealdQhrE97tf8xVLR7uM5X8voDmP3dzNU2P0A
Content-Type: application/json



###

PATCH  {{host}}/cardWalk/deleteW
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZkMTNmMjg3NjJhNGE2YTc3OTRlZWQiLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjp0cnVlLCJpYXQiOjE2NTIxMTIwMDN9.iMcVDCealdQhrE97tf8xVLR7uM5X8voDmP3dzNU2P0A
Content-Type: application/json

{
    "fDogWalker":["2344545","dfsdfgdfg","2334545"]
}



